### ISSUE TITLE
Errors due to ethereal biome being removed from Biomes 'O Plenty.

### ISSUE THREAD

**Issue by grokkingit** [Markus1002/Extra-Boats#7]
Hi,

I'm seeing errors for the ethereal boat types (large, chest and furnace) when starting up my server. I checked in on the BOP discord and someone confirmed that the ethereal biome no longer exists (I also couldn't find it when I had a scratch through the source).

Extra-Boats: extraboats-1.3.5-1.15.2
BOP: BiomesOPlenty-1.15.2-10.0.0.363
Server: forge-1.15.2-31.2.0

Thanks
Guy

`[16:24:44] [Server thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe extraboats:large_ethereal_boat
com.google.gson.JsonSyntaxException: Unknown item 'biomesoplenty:ethereal_planks'
        at net.minecraft.item.crafting.Ingredient.lambda$deserializeItemList$12(Ingredient.java:214) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_252] {}
        at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:213) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?] {re:classloading}
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:187) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.item.crafting.ShapedRecipe.func_192408_a(ShapedRecipe.java:254) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipe.java:24) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:278) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner
:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner
:A}
        at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:363) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A
}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
`

`[16:24:46] [Server thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading custom advancement extraboats:recipes/large_ethereal_boat: Unknown it
em id 'biomesoplenty:ethereal_boat'`

**Comment by Markus1002** [comment]
Fixed in 1.4.0.
