### ISSUE TITLE
boatload-1.20.1-5.0.1 crash on server start

### ISSUE THREAD

**Issue by VsUK** [Markus1002/Extra-Boats#86]
Can't seem to get this to load on my forge 1.20.1 server. It crashes on start up.

`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [boatload.mixins.json:BoatMixin from mod (unknown)] from phase [DEFAULT] in config [boatload.mixins.json] FAILED during APPLY
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
        ... 33 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> boatload.mixins.json:BoatMixin from mod (unknown) -> Apply Methods -> ()Lnet/minecraft/world/item/ItemStack;:getBanner -> Transform Instructions -> CHECKCAST com/teamabnormals/blueprint/common/world/storage/tracking/IDataManager -> desc=com/teamabnormals/blueprint/common/world/storage/tracking/IDataManager]`

**Comment by bageldotjpg** [comment]
Closing due to lack of full log and unable to reproduce. Make sure you have blueprint and boatload instaalled and both are up to date.
